### ISSUE TITLE
Uncaught User is not logged in when user is logged in

### ISSUE THREAD

**Issue by isAlmogK** [maxkferg/meteor-facebook-collections#2]
I'm getting Uncaught User is not logged in but the user is logged in and was done thru facebook

**Comment by maxkferg** [comment]
I’ll test this out with the latest version of Meteor in the next few days. Until then, check that the user has a facebook access token (Meteor.user().services.facebook.access_token if I recall correctly).  

From: Almog Koren
Sent: ‎Wednesday‎, ‎22‎ ‎October‎ ‎2014 ‎12‎:‎33‎ ‎p.m.
To: maxkferg/meteor-facebook-collections

I'm getting Uncaught User is not logged in but the user is logged in and was done thru facebook

**Comment by isAlmogK** [comment]
Yea the user has an access token, but no worries.

**Comment by matb33** [comment]
The server needs to publish the accessToken to the client.
