### ISSUE TITLE
User is not logged in 

### ISSUE THREAD

**Issue by belokonm** [maxkferg/meteor-facebook-collections#4]
Hi. Can you help with configuration. I've created simple empty project and add accounts-facebook. 
In html I've added {{> loginButtons}}. Created API + secret key. And see that name from FB is appear. 
In js I have
if (Meteor.isClient) {
  var MyPosts = FacebookCollections.getPosts("me",300);
  MyPosts.observe({
    "added":function(){
    var photos = MyPosts.findOne({type:"photo"});
    console.log(photos);
    }
  });
}
As a result shows user is not loggedin. 
Did I miss some hook? 
Thx.

**Comment by maxkferg** [comment]
FacebookCollections checks for a Facebook accessToken before calling to the facebook API.
Check that your user has that accessToken by running Meteor.user().services.facebook.accessToken from the console. If the access token is not present then the "\* not logged in error" will be thrown.

Let me know if the user does have an accessToken - then I will look into this furthur

**Comment by belokonm** [comment]
Hi Max. Thank you for answer, but I can't manage to work it in proper way. Same error. Can you share some example how you managing publish for Meteor.user().services.facebook.accessToken ?
My current js:
if (Meteor.isClient) {
Meteor.subscribe("userData");
var MyPosts = FacebookCollections.getPosts("me",300);
Tracker.autorun(function () {
    console.log(MyPosts.find().fetch());
});
}

if (Meteor.isServer) {
    //services.facebook.accessToken;
  Meteor.publish("userData", function () {
  if (this.userId) {
    return Meteor.users.find({_id: this.userId},
                             {fields: {'services': 1}});
  } else {
    this.ready();
  }
});
}

**Comment by belokonm** [comment]
Max?

**Comment by maxkferg** [comment]
Have a look at how facebook-collections is integrated with https://github.com/NitroLabs/meteor-oauth-demo. Specifically look at the meteor-oauth.js file. It is very simple but it should have what you need. This demo is also serving at http://nitro-oauth-demo.meteor.com/. The only difference between my code and yours is that I wrap my Meteor.subscribe("userData") call with Tracker.autorun.

**Comment by belokonm** [comment]
Hi. When I try yours example Chrome back js error - Uncaught TypeError: undefined is not a function  (7b810172bfb7adf790cb0b85460f43b21404f695.js:136) and in the source code I did not found how to use FB collection. Can you check if on github u have the latest version?

**Comment by maxkferg** [comment]
Login with facebook on the demo and run the following commands in the console:
var MyPosts = FacebookCollections.getPosts("me",100)
MyPosts.find().fetch()

I think the problems you are having are related to the fact that the MyPosts collection can not be created until the user has logged in. Meteor has no easy way to catch the login event, so it is hard to initialize the MyPosts Collection at the correct time. I have opened issue #5 to deal with this problem. Suggestions are very welcome.
